version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: digitalocean.com/php
    restart: unless-stopped
    # container_name: app
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./projeto:/var/www/
      - ./dockerconfig/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
  server:
    image: nginx:alpine
    restart: unless-stopped
    # container_name: webserver
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./projeto:/var/www/
      - ./dockerconfig/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
  db:
    # container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: data
      MYSQL_ROOT_PASSWORD: rootroot
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql/
    networks: 
      - app-network
  workdb:
    image: phpmyadmin/phpmyadmin
    ports:
      - 81:80
    environment: 
      PMA_ARBITRARY: 1  
    networks: 
      - app-network
  

#Docker Networks
networks:
  app-network:
    driver: bridge